[package]
name = "init-templates"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
antora-project = { path = "../antora-project" }
antora-fs = { path = "../antora-fs" }
relative-path = { path = "../relative-path" }
init-task = { path = "../init-task" }