[package]
name = "init-task"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
antora-fs = { path = "../antora-fs" }
antora-project = { path = "../antora-project" }
relative-path = { path = "../relative-path" }
antora-process = { path="../antora-process" }